// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_desktop/test/features/cash_register/providers/cash_register_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:frontend_desktop/features/cash_register/domain/entities/cash_register_shift.dart'
    as _i3;
import 'package:frontend_desktop/features/cash_register/domain/repositories/cash_register_repository.dart'
    as _i2;
import 'package:frontend_desktop/features/cash_register/domain/usecases/close_shift_usecase.dart'
    as _i7;
import 'package:frontend_desktop/features/cash_register/domain/usecases/get_current_shift_usecase.dart'
    as _i4;
import 'package:frontend_desktop/features/cash_register/domain/usecases/open_shift_usecase.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCashRegisterRepository_0 extends _i1.SmartFake
    implements _i2.CashRegisterRepository {
  _FakeCashRegisterRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCashRegisterShift_1 extends _i1.SmartFake
    implements _i3.CashRegisterShift {
  _FakeCashRegisterShift_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCurrentShiftUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentShiftUseCase extends _i1.Mock
    implements _i4.GetCurrentShiftUseCase {
  MockGetCurrentShiftUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CashRegisterRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCashRegisterRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CashRegisterRepository);

  @override
  _i5.Future<_i3.CashRegisterShift?> call({int? registerId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#registerId: registerId},
        ),
        returnValue: _i5.Future<_i3.CashRegisterShift?>.value(),
      ) as _i5.Future<_i3.CashRegisterShift?>);
}

/// A class which mocks [OpenShiftUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenShiftUseCase extends _i1.Mock implements _i6.OpenShiftUseCase {
  MockOpenShiftUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CashRegisterRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCashRegisterRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CashRegisterRepository);

  @override
  _i5.Future<_i3.CashRegisterShift> call(
    double? openingBalance,
    int? userId, [
    int? registerId,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            openingBalance,
            userId,
            registerId,
          ],
        ),
        returnValue:
            _i5.Future<_i3.CashRegisterShift>.value(_FakeCashRegisterShift_1(
          this,
          Invocation.method(
            #call,
            [
              openingBalance,
              userId,
              registerId,
            ],
          ),
        )),
      ) as _i5.Future<_i3.CashRegisterShift>);
}

/// A class which mocks [CloseShiftUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloseShiftUseCase extends _i1.Mock implements _i7.CloseShiftUseCase {
  MockCloseShiftUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CashRegisterRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCashRegisterRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CashRegisterRepository);

  @override
  _i5.Future<_i3.CashRegisterShift> call(
    int? shiftId,
    double? countedCash, {
    int? closerUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            shiftId,
            countedCash,
          ],
          {#closerUserId: closerUserId},
        ),
        returnValue:
            _i5.Future<_i3.CashRegisterShift>.value(_FakeCashRegisterShift_1(
          this,
          Invocation.method(
            #call,
            [
              shiftId,
              countedCash,
            ],
            {#closerUserId: closerUserId},
          ),
        )),
      ) as _i5.Future<_i3.CashRegisterShift>);
}
