// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_desktop/test/features/pos/providers/pos_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i10;

import 'package:frontend_desktop/core/providers/local_terminal_provider.dart'
    as _i11;
import 'package:frontend_desktop/core/utils/receipt_printer_service.dart'
    as _i4;
import 'package:frontend_desktop/features/cash_register/domain/entities/cash_register_shift.dart'
    as _i14;
import 'package:frontend_desktop/features/catalog/domain/entities/product.dart'
    as _i9;
import 'package:frontend_desktop/features/pos/domain/entities/cart_item.dart'
    as _i7;
import 'package:frontend_desktop/features/pos/domain/entities/sale.dart' as _i3;
import 'package:frontend_desktop/features/pos/domain/repositories/pos_repository.dart'
    as _i2;
import 'package:frontend_desktop/features/pos/domain/usecases/process_sale_usecase.dart'
    as _i5;
import 'package:frontend_desktop/features/pos/domain/usecases/search_products_usecase.dart'
    as _i8;
import 'package:frontend_desktop/features/quotes/data/quote_repository.dart'
    as _i12;
import 'package:frontend_desktop/features/settings/domain/entities/business_settings.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePosRepository_0 extends _i1.SmartFake implements _i2.PosRepository {
  _FakePosRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSale_1 extends _i1.SmartFake implements _i3.Sale {
  _FakeSale_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrinterConfig_2 extends _i1.SmartFake implements _i4.PrinterConfig {
  _FakePrinterConfig_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProcessSaleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessSaleUseCase extends _i1.Mock
    implements _i5.ProcessSaleUseCase {
  MockProcessSaleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PosRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePosRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PosRepository);

  @override
  _i6.Future<_i3.Sale> call({
    required double? total,
    required double? totalSurcharge,
    List<Map<String, dynamic>>? payments,
    double? tenderedAmount,
    double? changeAmount,
    required int? shiftId,
    required List<_i7.CartItem>? items,
    int? userId,
    int? customerId,
    int? quoteId,
    String? status = 'completed',
    double? shippingCost = 0.0,
    bool? requiresDispatch = false,
    String? fulfillmentStatus = 'pending',
    Map<String, dynamic>? checkDetails,
    String? deliveryAddress,
    String? priceList,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #total: total,
            #totalSurcharge: totalSurcharge,
            #payments: payments,
            #tenderedAmount: tenderedAmount,
            #changeAmount: changeAmount,
            #shiftId: shiftId,
            #items: items,
            #userId: userId,
            #customerId: customerId,
            #quoteId: quoteId,
            #status: status,
            #shippingCost: shippingCost,
            #requiresDispatch: requiresDispatch,
            #fulfillmentStatus: fulfillmentStatus,
            #checkDetails: checkDetails,
            #deliveryAddress: deliveryAddress,
            #priceList: priceList,
          },
        ),
        returnValue: _i6.Future<_i3.Sale>.value(_FakeSale_1(
          this,
          Invocation.method(
            #call,
            [],
            {
              #total: total,
              #totalSurcharge: totalSurcharge,
              #payments: payments,
              #tenderedAmount: tenderedAmount,
              #changeAmount: changeAmount,
              #shiftId: shiftId,
              #items: items,
              #userId: userId,
              #customerId: customerId,
              #quoteId: quoteId,
              #status: status,
              #shippingCost: shippingCost,
              #requiresDispatch: requiresDispatch,
              #fulfillmentStatus: fulfillmentStatus,
              #checkDetails: checkDetails,
              #deliveryAddress: deliveryAddress,
              #priceList: priceList,
            },
          ),
        )),
      ) as _i6.Future<_i3.Sale>);
}

/// A class which mocks [SearchProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchProductsUseCase extends _i1.Mock
    implements _i8.SearchProductsUseCase {
  MockSearchProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PosRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePosRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PosRepository);

  @override
  _i6.Future<List<_i9.Product>> call(String? query) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [query],
        ),
        returnValue: _i6.Future<List<_i9.Product>>.value(<_i9.Product>[]),
      ) as _i6.Future<List<_i9.Product>>);
}

/// A class which mocks [PosRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPosRepository extends _i1.Mock implements _i2.PosRepository {
  MockPosRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i9.Product>> searchProducts(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [query],
        ),
        returnValue: _i6.Future<List<_i9.Product>>.value(<_i9.Product>[]),
      ) as _i6.Future<List<_i9.Product>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> fetchPaymentMethods() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPaymentMethods,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<_i3.Sale> processSale({
    required double? total,
    required double? totalSurcharge,
    List<Map<String, dynamic>>? payments,
    double? tenderedAmount,
    double? changeAmount,
    required int? shiftId,
    required List<_i7.CartItem>? items,
    int? userId,
    int? customerId,
    int? quoteId,
    String? status = 'completed',
    double? shippingCost = 0.0,
    bool? requiresDispatch = false,
    String? fulfillmentStatus = 'pending',
    Map<String, dynamic>? checkDetails,
    String? deliveryAddress,
    String? priceList,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processSale,
          [],
          {
            #total: total,
            #totalSurcharge: totalSurcharge,
            #payments: payments,
            #tenderedAmount: tenderedAmount,
            #changeAmount: changeAmount,
            #shiftId: shiftId,
            #items: items,
            #userId: userId,
            #customerId: customerId,
            #quoteId: quoteId,
            #status: status,
            #shippingCost: shippingCost,
            #requiresDispatch: requiresDispatch,
            #fulfillmentStatus: fulfillmentStatus,
            #checkDetails: checkDetails,
            #deliveryAddress: deliveryAddress,
            #priceList: priceList,
          },
        ),
        returnValue: _i6.Future<_i3.Sale>.value(_FakeSale_1(
          this,
          Invocation.method(
            #processSale,
            [],
            {
              #total: total,
              #totalSurcharge: totalSurcharge,
              #payments: payments,
              #tenderedAmount: tenderedAmount,
              #changeAmount: changeAmount,
              #shiftId: shiftId,
              #items: items,
              #userId: userId,
              #customerId: customerId,
              #quoteId: quoteId,
              #status: status,
              #shippingCost: shippingCost,
              #requiresDispatch: requiresDispatch,
              #fulfillmentStatus: fulfillmentStatus,
              #checkDetails: checkDetails,
              #deliveryAddress: deliveryAddress,
              #priceList: priceList,
            },
          ),
        )),
      ) as _i6.Future<_i3.Sale>);

  @override
  _i6.Future<List<Map<String, dynamic>>> fetchPendingSales() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPendingSales,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<Map<String, dynamic>> payPendingSale({
    required int? saleId,
    required double? totalSurcharge,
    required List<Map<String, dynamic>>? payments,
    required double? tenderedAmount,
    required double? changeAmount,
    required int? shiftId,
    int? userId,
    List<_i7.CartItem>? items,
    double? shippingCost = 0.0,
    Map<String, dynamic>? checkDetails,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #payPendingSale,
          [],
          {
            #saleId: saleId,
            #totalSurcharge: totalSurcharge,
            #payments: payments,
            #tenderedAmount: tenderedAmount,
            #changeAmount: changeAmount,
            #shiftId: shiftId,
            #userId: userId,
            #items: items,
            #shippingCost: shippingCost,
            #checkDetails: checkDetails,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> voidPendingSale(int? saleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #voidPendingSale,
          [saleId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> updatePaymentMethodSurcharge(
    int? id,
    double? surchargeValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePaymentMethodSurcharge,
          [
            id,
            surchargeValue,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i10.Uint8List> downloadTicketPdf(int? saleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadTicketPdf,
          [saleId],
        ),
        returnValue: _i6.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
      ) as _i6.Future<_i10.Uint8List>);

  @override
  _i6.Future<Map<String, dynamic>> createDeliveryNoteFromSale(
    int? saleId, {
    String? fulfillmentStatus = 'pending',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDeliveryNoteFromSale,
          [saleId],
          {#fulfillmentStatus: fulfillmentStatus},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [ReceiptPrinterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReceiptPrinterService extends _i1.Mock
    implements _i4.ReceiptPrinterService {
  MockReceiptPrinterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PrinterConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakePrinterConfig_2(
          this,
          Invocation.getter(#config),
        ),
      ) as _i4.PrinterConfig);

  @override
  set config(_i4.PrinterConfig? value) => super.noSuchMethod(
        Invocation.setter(
          #config,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> reconfigure(_i11.LocalTerminalProvider? localTerminal) =>
      (super.noSuchMethod(
        Invocation.method(
          #reconfigure,
          [localTerminal],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> openCashDrawer(_i11.LocalTerminalProvider? localTerminal) =>
      (super.noSuchMethod(
        Invocation.method(
          #openCashDrawer,
          [localTerminal],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> printQuoteTicket({
    required _i12.Quote? quote,
    required _i13.BusinessSettings? settings,
    required _i11.LocalTerminalProvider? localTerminal,
    required String? vendorName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #printQuoteTicket,
          [],
          {
            #quote: quote,
            #settings: settings,
            #localTerminal: localTerminal,
            #vendorName: vendorName,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> printSaleTicket({
    required List<_i7.CartItem>? items,
    required double? total,
    required _i13.BusinessSettings? settings,
    required _i11.LocalTerminalProvider? localTerminal,
    String? paymentMethod = 'EFECTIVO',
    List<Map<String, dynamic>>? paymentDetails = const [],
    String? receiptNumber,
    String? userName,
    String? cashierName,
    double? surchargeAmount = 0.0,
    double? tenderedAmount = 0.0,
    double? changeAmount = 0.0,
    double? shippingCost = 0.0,
    String? paperSizeOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #printSaleTicket,
          [],
          {
            #items: items,
            #total: total,
            #settings: settings,
            #localTerminal: localTerminal,
            #paymentMethod: paymentMethod,
            #paymentDetails: paymentDetails,
            #receiptNumber: receiptNumber,
            #userName: userName,
            #cashierName: cashierName,
            #surchargeAmount: surchargeAmount,
            #tenderedAmount: tenderedAmount,
            #changeAmount: changeAmount,
            #shippingCost: shippingCost,
            #paperSizeOverride: paperSizeOverride,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> printSplitTicket({
    required List<_i7.CartItem>? items,
    required double? total,
    required double? shippingCost,
    required _i13.BusinessSettings? settings,
    required _i11.LocalTerminalProvider? localTerminal,
    required Map<String, dynamic>? deliveryNote,
    List<Map<String, dynamic>>? paymentDetails = const [],
    String? receiptNumber,
    String? deliveryNoteNumber,
    String? userName,
    String? cashierName,
    double? surchargeAmount = 0.0,
    double? tenderedAmount = 0.0,
    double? changeAmount = 0.0,
    String? customerName,
    String? paperSizeOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #printSplitTicket,
          [],
          {
            #items: items,
            #total: total,
            #shippingCost: shippingCost,
            #settings: settings,
            #localTerminal: localTerminal,
            #deliveryNote: deliveryNote,
            #paymentDetails: paymentDetails,
            #receiptNumber: receiptNumber,
            #deliveryNoteNumber: deliveryNoteNumber,
            #userName: userName,
            #cashierName: cashierName,
            #surchargeAmount: surchargeAmount,
            #tenderedAmount: tenderedAmount,
            #changeAmount: changeAmount,
            #customerName: customerName,
            #paperSizeOverride: paperSizeOverride,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> printDeliveryNoteTicket({
    required Map<String, dynamic>? note,
    required List<Map<String, dynamic>>? deliveredItemsData,
    required _i13.BusinessSettings? settings,
    required _i11.LocalTerminalProvider? localTerminal,
    String? customerName,
    String? vendorName,
    String? dispatcherName,
    bool? isReprint = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #printDeliveryNoteTicket,
          [],
          {
            #note: note,
            #deliveredItemsData: deliveredItemsData,
            #settings: settings,
            #localTerminal: localTerminal,
            #customerName: customerName,
            #vendorName: vendorName,
            #dispatcherName: dispatcherName,
            #isReprint: isReprint,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> printZCloseTicket({
    required _i14.CashRegisterShift? shift,
    required _i13.BusinessSettings? settings,
    required _i11.LocalTerminalProvider? localTerminal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #printZCloseTicket,
          [],
          {
            #shift: shift,
            #settings: settings,
            #localTerminal: localTerminal,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
